stages:
  - build
  - test

before_script:
  - nuget restore

cache:
 key: "$CI_PIPELINE_ID"
 untracked: true

build_client:
 stage: build
 script:
    - msbuild "Client/Client.csproj"

build_cui:
 stage: build
 script:
    - msbuild "Client/Client.csproj"
    - msbuild "CUIClient/CUIClient.csproj"

build_epspwpf:
 stage: build
 script:
    - msbuild "Client/Client.csproj"
    - msbuild "EPSPWPFClient/EPSPWPFClient.csproj"
 allow_failure: true

test_client:
 stage: test
 script:
    - msbuild "Client/Client.csproj"
    - msbuild "ClientTest/ClientTest.csproj"
    - nunit-console ClientTest/bin/Debug/ClientTest.dll
